Debug-Log Controller: avoid Exception on non-existing Channel (#979)
If a configured `additionalChannel` does not exist - e.g. during startup phase or when with wrong configuration - a stacktrace appeared. This PR handles the error gracefully by logging "CHANNEL_IS_NOT_DEFINED" in this case. See JUnit test for a example.

```
java.lang.IllegalArgumentException: Channel [Tower0Module1SerialNumber] is not defined for ID [battery0]. Implementation [io.openems.edge.battery.fenecon.home.BatteryFeneconHomeImpl]
        at io.openems.edge.common.component.OpenemsComponent.channel(OpenemsComponent.java:153)
        at io.openems.edge.controller.debuglog.ControllerDebugLogImpl.lambda$getLogMessage$2(ControllerDebugLogImpl.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
        at io.openems.edge.controller.debuglog.ControllerDebugLogImpl.getLogMessage(ControllerDebugLogImpl.java:138)
        at io.openems.edge.controller.debuglog.ControllerDebugLogImpl.run(ControllerDebugLogImpl.java:110)
        at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:114)
        at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156)
```

Reviewed-on: https://git.intranet.fenecon.de/FENECON/fems/pulls/979
Reviewed-by: Sebastian Asen <sebastian.asen@fenecon.de>