FEMS Backports 2025-02-02 (#2997)
* UI
  * Change display color of currency axes
    - fix coloring of yAxes for currency
    - extending eslint rule [`no-unused-vars`](https://eslint.org/docs/latest/rules/no-unused-vars#ignorerestsiblings) with `ignoreRestSiblings`: destructuring throws otherwise an error for unused sibling
  * Adjust custom time range chart display
    - Adjust time-range picker in mode `Custom` to display only the months queried for monthly resolution, before if start and endpoint are in a different year, it would fill up both years to show 12 months per year
  * Fix searchbar request overload
    - reducing calls of `GetEdgesRequest` and waiting for last requests response
    - avoids showing every response
    - introduce 1 second `debounce`
  * Refactor heat pump history
    - Using `Time`-channels for bar charts
    - creating refactored standalone unit tested lazy loaded history for heatpump
    - sanitizing data for io time channels if they are not adding up to
      - 24h (1 day - month view) -> rounding if only one minute missing
      - 744h (31 day month - year view) ... -> rounding if only one hour missing
      - -> increasing `RegularStateTime` by the missing diff
    - Attention: There still could be some deviation due to OpenEMS Edge being offline during systemupdate
  * Improve styling
    * Remove unused imports in GetNetworkInfo and MennekesEvcs
  * Controller.IO.Heating.Room: add UI Live widget
    - Add UI Live Flat and Modal for `Controller.IO.Heating.Room`
    - This implementation could in future serve as a proof of concept for new JSCalendar configurations
  * EVCS Cluster: remove slides from modal
    - Because of display errors after recent Angular & Ionic update.

* Edge
  * Host: extend getIpAddresses Request
    * Extended jsonRpc request for getIpAddresses with more data for networkInterfaces and IP routing table
  * Mennekes Relase: Remove AppPermissions
    * Remove App Permissions from Mennekes for upcoming release
  * SunSpec: set correct OpenemsType for floating point values
    * See commit details for an example of the changes for a Fronius PV Inverter with SunSpec Block 113
    * Originally we tried to avoid floating point in favour of integer numbers to avoid very frequent sending of changed values. This has been solved in the meantime with a DEFAULT_PERSISTENCE_PRIORITY of VERY_LOW for SunSpec channels.
  * ModbusTcp Read-Only: add modified handling
    * Adds modified method to ModbusTcp Read-Only
  * AppCenter: fix bug where all array properties cant be modified
    - Modifying array properties results in an error "expected array length 1 not 3"
    - "fixed" by changing order of checks to first check if property can be modified and then check if they are the same value
    - TODO future if access check on a array based property happens it needs to be modified to handle array values
    - remove excessive log if component does not exist in `ComponentManager#getComponentProperties`
  * Energy Optimizer: fix possible NPE
    - This fixes
```
[_energy ] ERROR [s.common.worker.AbstractWorker] Worker error. NullPointerException: Cannot invoke "io.jenetics.Genotype.get(int)" because "bestGt" is null
java.lang.NullPointerException: Cannot invoke "io.jenetics.Genotype.get(int)" because "bestGt" is null
```
    - According to docs the Collector can indeed return `null`: https://github.com/jenetics/jenetics/blob/master/jenetics/src/main/java/io/jenetics/engine/EvolutionResult.java#L475-L476
  * ElectricityMeter: added calculateCurrentsFromActivePowerAndVoltage and calculatePhasesFromVoltage
    - ElectricityMeter enhancement for more easier integration of future EVCSs. Method may be useful for general ElectricityMeter implementations as well. That's why it was placed in ElectricityMeter and not in Evcs.
  * Windows Fix for IP Validation in Apps
    - IP Validation Regex is now Compatible with Windows again. (Currently when OpenEMS is run locally apps with IP Validation can't be installed)
  * GoodWeGridMeter: ElementToChannelConverter NP-Fix
    - Null check in element to channel converter
  * GoodWe: improve Battery Power Settings
    - Some of the Power settings for the goodwe were not applied correctly (Per default disabled, wrong scale factors, wrong register mapping cosPhiF != PU)
  * GoodWe: ignore impossible power values
    - The DcActivePower resgister of GoodWe is giving 20-40 watt values when the SoC is 0 or 100 and there is no real charge/discharge of the battery happening. This values will be ignored to avoid wrong energy values, as the energy is calculated based on the active power.
    - The same occurs when the battery is getting a 0 charge/discharge set point. If the SoC is between 0 and 100 it is also ignoring this low power values when the current EmsPowerMode is Charge/Discharge Bat & the EmsPowerSet is 0 W

---------

Co-authored-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
Co-authored-by: Lukas Rieger <73471197+lukasrgr@users.noreply.github.com>
Co-authored-by: Johann Kaufmann <165755282+johannk24@users.noreply.github.com>
Co-authored-by: Michael Grill <59126309+michaelgrill@users.noreply.github.com>
Co-authored-by: Fabian Brandtner <10850256+fabian94533@users.noreply.github.com>
Co-authored-by: Sebastian Asen <47855186+sebastianasen@users.noreply.github.com>
Co-authored-by: Christian Lehne <51822163+clehne@users.noreply.github.com>