AppCenter: fix not automatically installing missing dependencies (#929)
user is null while resolving missing dependencies which resulted in a NullPointerException

```
2023-11-15T12:13:02,237 [orker-10] ERROR [appmanager.ResolveDependencies] Could not resolve dependencies!
java.lang.NullPointerException: Cannot invoke "io.openems.edge.common.user.User.getLanguage()" because "<parameter1>" is null
	at io.openems.edge.core.appmanager.AppManagerImpl.lambda$15(AppManagerImpl.java:517) ~[?:?]
	at io.openems.edge.core.appmanager.AppManagerImpl.lockModifyingApps(AppManagerImpl.java:892) ~[?:?]
	at io.openems.edge.core.appmanager.AppManagerImpl.handleAddAppInstanceRequest(AppManagerImpl.java:515) ~[?:?]
	at io.openems.edge.core.appmanager.ResolveDependencies.resolveDependencies(ResolveDependencies.java:108) ~[?:?]
	at io.openems.edge.core.appmanager.ResolveDependencies.run(ResolveDependencies.java:42) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
Everything still works there will only be AppCenter info and debugLog of a missing dependency if there are missing dependencies

Reviewed-on: https://git.intranet.fenecon.de/FENECON/fems/pulls/929
Reviewed-by: Hueseyin Sahutoglu <hueseyin.sahutoglu@fenecon.de>
Reviewed-by: Stefan Feilmeier <stefan.feilmeier@fenecon.de>
Co-authored-by: Michael Grill <michael.grill@fenecon.de>
Co-committed-by: Michael Grill <michael.grill@fenecon.de>