FEMS Backports
* UI: refactor channelthreshold history

  * Example for all relay data dependent charts -> active time over period
  * added time to Chart types
  * notice that older fems that do not have this channel, are not showing anything on month or year currently

* User: adding JsonObject for UI "settings"

* GoodWe Grid-Meter: if HAS_NO_METER is set, set values to 'null'

  * If 'HAS_NO_METER' is set, values are set to 'UNDEFINED' instead of 'zero'.
  * Logic is largely copied from FENECON Commercial Battery. Should possibly be also applied to Charger 'HAS_NO_DC_PV'.

* Modbus Bridge TasksSupplier: avoid ConcurrentModificationException

  * Synchronizing access to `this.taskManagers` to avoid this error:
```
[_cycle  ] ERROR [org.apache.felix.eventadmin   ] EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=io/openems/edge/cycle/BEFORE_PROCESS_IMAGE]>
java.util.ConcurrentModificationException: null
        at java.util.HashMap.forEach(Unknown Source) ~[?:?]
        at io.openems.edge.bridge.modbus.api.worker.internal.TasksSupplierImpl.getOneLowPriorityReadTask(TasksSupplierImpl.java:114) ~[?:?]
        at io.openems.edge.bridge.modbus.api.worker.internal.TasksSupplierImpl.getCycleTasks(TasksSupplierImpl.java:57) ~[?:?]
        at io.openems.edge.bridge.modbus.api.worker.internal.CycleTasksManager.onBeforeProcessImage(CycleTasksManager.java:90) ~[?:?]
        at io.openems.edge.bridge.modbus.api.worker.ModbusWorker.onBeforeProcessImage(ModbusWorker.java:165) ~[?:?]
        at io.openems.edge.bridge.modbus.api.AbstractModbusBridge.handleEvent(AbstractModbusBridge.java:132) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:432) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutDenylistTiming(HandlerTask.java:82) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:107) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:155) ~[?:?]
        at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96) ~[?:?]
        at io.openems.common.event.EventBuilder.send(EventBuilder.java:68) ~[?:?]
        at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:50) ~[?:?]
        at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156) ~[?:?]
```

* UI: channelthreshold: use factory instead of nature

  * add missing import of ```controller```
  * change checking for nature to factory

* StateChannels: always set initial value to false

  * Use case: `MODBUS_COMMUNICATION_FAILED` must always be defined to avoid:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.openems.edge.common.channel.value.Value.get()" is null
        at io.openems.edge.bridge.modbus.api.ModbusComponent.getModbusCommunicationFailed(ModbusComponent.java:56) ~[?:?]
        at io.openems.edge.battery.fenecon.home.BatteryFeneconHomeImpl.handleStateMachine(BatteryFeneconHomeImpl.java:170) ~[?:?]
        at io.openems.edge.battery.fenecon.home.BatteryFeneconHomeImpl.handleEvent(BatteryFeneconHomeImpl.java:148) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:432) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutDenylistTiming(HandlerTask.java:82) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:107) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:155) ~[?:?]
        at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96) ~[?:?]
        at io.openems.common.event.EventBuilder.send(EventBuilder.java:68) ~[?:?]
        at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:77) ~[?:?]
        at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156) ~[?:?]
```

  * Solving this, by generally always initialize StateChannels with `false` and apply `initialValue` immediately.

  * Future ToDo: all Nature methods for StateChannels should return `boolean` instead of `Boolean`.

* ESS Power: handle other possible Exceptions

  * At the touched positions more than the listed Exceptions can happen, e.g. `ArrayIndexOutOfBoundsException` or `TooManyIterationsException`. This handles all of them properly.

  * Detected via this Stacktrace:
```
[_cycle  ] ERROR [org.apache.felix.eventadmin   ] EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=io/openems/edge/cycle/BEFORE_WRITE] {} | [i>
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.openems.edge.ess.core.power.optimizers.AddConstraintsForNotStrictlyDefinedCoefficients.apply(AddConstraintsForNotStrictlyDefinedCoefficients.java:61) ~[?:?]
        at io.openems.edge.ess.core.power.Solver.solve(Solver.java:138) ~[?:?]
        at io.openems.edge.ess.core.power.EssPowerImpl.handleEvent(EssPowerImpl.java:221) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:432) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutDenylistTiming(HandlerTask.java:82) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:107) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:155) ~[?:?]
        at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96) ~[?:?]
        at io.openems.common.event.EventBuilder.send(EventBuilder.java:68) ~[?:?]
        at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:154) ~[?:?]
        at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156) ~[?:?]
```

Co-authored-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
Reviewed-by: Sebastian Asen <47855186+sebastianasen@users.noreply.github.com>

* Debug-Log Controller: avoid Exception on non-existing Channel

If a configured `additionalChannel` does not exist - e.g. during startup phase or when with wrong configuration - a stacktrace appeared. This PR handles the error gracefully by logging "CHANNEL_IS_NOT_DEFINED" in this case. See JUnit test for a example.

```
java.lang.IllegalArgumentException: Channel [Tower0Module1SerialNumber] is not defined for ID [battery0]. Implementation [io.openems.edge.battery.fenecon.home.BatteryFeneconHomeImpl]
        at io.openems.edge.common.component.OpenemsComponent.channel(OpenemsComponent.java:153)
        at io.openems.edge.controller.debuglog.ControllerDebugLogImpl.lambda$getLogMessage$2(ControllerDebugLogImpl.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
        at io.openems.edge.controller.debuglog.ControllerDebugLogImpl.getLogMessage(ControllerDebugLogImpl.java:138)
        at io.openems.edge.controller.debuglog.ControllerDebugLogImpl.run(ControllerDebugLogImpl.java:110)
        at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:114)
        at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156)
```

* GoodWe BatteryInverter: write certain Channels only on activate/modified

  * Some Channels were still written on every Cycle
  * `Execute failed FC16WriteRegisters [batteryInverter0;unitid=247;ref=45251/0xb0c3;length=3] ModbusSlaveException: Illegal Data Address `

* UI: add notifcation component

  * Implemented for showing information, warning etc only ***once***
  * Show warning, info only once
  * If already seen, save in localStorage

* Use static import for Dummy-Users

* Cleanup for OEM; simplifies merges with OpenEMS

  * Move App-Center Master-Key to OEM
  * Move Website-URLs to OEM -> this will get refactored again for sure; but it serves the purpose for now
  * Use static imports
  * Move KACO 10 IdentKey to OEM
  * Move ENTSO-E Token to OEM
  * Move Exchangerate.host Access-Key to OEM

---------

Co-authored-by: Lukas Rieger <73471197+lukasrgr@users.noreply.github.com>
Co-authored-by: Michael Grill <59126309+michaelgrill@users.noreply.github.com>
Co-authored-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
Co-authored-by: Sebastian Asen <47855186+sebastianasen@users.noreply.github.com>
Co-authored-by: Hueseyin Sahutoglu <34771592+huseyinsaht@users.noreply.github.com>