FEMS Backports 2025-07-12 (#3236)
* UI
  * E-Mobility: Fix Read-Write
    - checking for true and then inverting value (value is false if no part of config and default value has to be true)
  * E-Mobility: Fix Non Deprecated EVCS in History
    - fix filters for evcs in history flat
  * Refactor Timeslot-, Asymmetric- and Symmetric peakshaving history
    - Refactoring peakshaving history,
    - adding `SOC` to chart
    - change `measured value` to be reference value of registered meter
  * Add missing storage flat component
    - Add missing storage flat component in `/history`, removed by accident before

* Edge
  * Fix Modified is not called on UpdateComponentConfig
    - Reset '.target' Property only if really required, because unnecessary reset of '.target' properties triggers the Component to be destroyed (i.e. @Deactivate + @Activate) instead of reused (via @Modified)
  * SunSpec: skip duplicated sunspec blocks
    - Common block kept reappearing after the first common block, which caused that these models are created again with their channels and duplicated channels caused a exception so that sunspec never completes
    - added exception log
    - skip duplicated models
  * Move KEBA+HardyBarth EVCS to EVSE bundles
    - This will allow us to share common files in future.
    - This also adjusts KEBA EVSE Config description for P30 / P40
      - P30 will only be supported via UDP (even though latest P30 also support Modbus/TCP, the protocol is slightly different to the one of P40)
      - P40 will only be supported via Modbus/TCP
  * KEBA improvements
    - Implement `readOnly` property
    - Use same `EvseChargePointKebaUdpCore`, `ChargeState`, `ReadWorker`, `CableState` for both implementations
    - Fix wrong Channel-Id that caused regular Exceptions
    - Implement Common FirmwareVersion and ActivePowerL1/L2/L3 calculation
  * E-Mobility: ReadOnly in KebaApp
    - Added readonly for keba udp in app. Normalized readonly for modbus.
  * Add support for FENECON 50kW battery inverter
  * PQ Plus UMD 96: calculate energy values
  * ChannelExportXlsxResponse: fix IllegalArgumentException
    - Before: 
    ```
    java.lang.IllegalArgumentException: Channel [SetEnable] is WRITE_ONLY.
            at io.openems.edge.common.channel.internal.AbstractReadChannel.value(AbstractReadChannel.java:202) ~[?:?]
            at io.openems.edge.core.componentmanager.jsonrpc.ChannelExportXlsxResponse.generatePayload(ChannelExportXlsxResponse.java:83) ~[?:?]
    ```
    - Move logic to static method
    - Add JUnit tests
    - Show full value for Enums
    - Add Type + Nature columns
  * EVCS: fix twice-plugging for KEBA in Cluster
    - The logic in EVCS Cluster only applied charge power after EV was in READY_FOR_CHARGING mode. It seems KEBA stations often do not switch to this state internally or the information is not sent properly via UDP. This often required plugging-unplugging-replugging the cable before a charging session would actually start.
    - We changed the logic to start applying charge power already in NOT_READY_FOR_CHARGING mode.
    - There is a little risk, that a fully loaded multi-EV charge park (with empty ESS) would still start charging and would be too slow reducing the overall power. But as this can always happen anyway (e.g. when a larger load is switched on), it is anyway handled in other parts of the code already.
  * AppCenter: Eastron Meter public available
    - remove beta tags for meter eastron app
    - rename app to be more generic "App.Meter.Eastron"
    - add app to tests
  * ENTSO-E: add ancillary costs for German law §14a EnWG Modul 3
  * Power2Heat: public release Askoma and myPV
    - Removed admin only permission
  * KEBA EVCS increase Plug Channel Priority
    - Make "Plug" channel persistence Priority HIGH to get real-time data in UI
    - Make sure "Plug" is properly set in both EVCS UDP and Modbus variants
  * Heating Element: add support for integrated consumption meter
    - Changes to the HeatingElement in the edge and in the UI.

* Backend
  * UiWebsocket: Implement a basic rate limiter for DoS protection
    - Exclude EdgeRpcRequest requests from rate limiting
    - Apply a separate, stricter limit for LogMessageNotification requests
  * Prometheus: log OpenEMS version in metrics
    - Track backend updates
    - Helps to find out if certain metrics correlate with a Backend update

Co-authored-by: Johann Kaufmann <165755282+johannk24@users.noreply.github.com>
Co-authored-by: Michael Grill <59126309+michaelgrill@users.noreply.github.com>
Co-authored-by: Sebastian Asen <47855186+sebastianasen@users.noreply.github.com>
Co-authored-by: Kai Jeschek <99220919+da-Kai@users.noreply.github.com>
Co-authored-by: Fabian Brandtner <10850256+fabian94533@users.noreply.github.com>
Co-authored-by: Lukas Rieger <73471197+lukasrgr@users.noreply.github.com>
Co-authored-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
Co-authored-by: Sagar Venu <32655208+venu-sagar@users.noreply.github.com>
Co-authored-by: DerMuaaa <102706922+DerMuaaa@users.noreply.github.com>
Co-authored-by: Leon Blenk <168936274+LaBlanko@users.noreply.github.com>