StateChannels: always set initial value to false
Use case: `MODBUS_COMMUNICATION_FAILED` must always be defined to avoid:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.openems.edge.common.channel.value.Value.get()" is null
        at io.openems.edge.bridge.modbus.api.ModbusComponent.getModbusCommunicationFailed(ModbusComponent.java:56) ~[?:?]
        at io.openems.edge.battery.fenecon.home.BatteryFeneconHomeImpl.handleStateMachine(BatteryFeneconHomeImpl.java:170) ~[?:?]
        at io.openems.edge.battery.fenecon.home.BatteryFeneconHomeImpl.handleEvent(BatteryFeneconHomeImpl.java:148) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:432) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutDenylistTiming(HandlerTask.java:82) ~[?:?]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:107) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:155) ~[?:?]
        at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96) ~[?:?]
        at io.openems.common.event.EventBuilder.send(EventBuilder.java:68) ~[?:?]
        at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:77) ~[?:?]
        at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156) ~[?:?]
```

Solving this, by generally always initialize StateChannels with `false` and apply `initialValue` immediately.

Future ToDo: all Nature methods for StateChannels should return `boolean` instead of `Boolean`.

Co-authored-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
Reviewed-by: Sebastian Asen <47855186+sebastianasen@users.noreply.github.com>