[Edge] Fix parseIpJson for Debian 9
Before a IndexOutOfBoundsException was thrown, which caused App Center install to fail

```
2025-08-09T19:01:59,431 [ckend0-0] ERROR [.common.jsonapi.JsonApiBuilder] Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at com.google.gson.JsonArray.get(JsonArray.java:232) ~[?:?]
        at io.openems.edge.core.host.OperatingSystemDebianSystemd.parseIpJson(OperatingSystemDebianSystemd.java:640) ~[?:?]
        at io.openems.edge.core.host.OperatingSystemDebianSystemd.parseShowJson(OperatingSystemDebianSystemd.java:672) ~[?:?]
        at io.openems.edge.core.host.OperatingSystemDebianSystemd.getSystemIPs(OperatingSystemDebianSystemd.java:614) ~[?:?]
        at io.openems.edge.core.host.HostImpl.getSystemIPs(HostImpl.java:215) ~[?:?]
        at io.openems.edge.app.common.props.CommunicationProps.lambda$excludingIp$6(CommunicationProps.java:80) ~[?:?]
        at io.openems.edge.core.appmanager.AppDef.lambda$setField$6(AppDef.java:698) ~[?:?]
        at io.openems.edge.core.appmanager.AppDef.lambda$getField$18(AppDef.java:922) ~[?:?]
        at io.openems.edge.core.appmanager.AbstractOpenemsAppWithProps.lambda$getAppAssistant$16(AbstractOpenemsAppWithProps.java:210) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at io.openems.edge.core.appmanager.AbstractOpenemsAppWithProps.getAppAssistant(AbstractOpenemsAppWithProps.java:214) ~[?:?]
        at io.openems.edge.core.appmanager.AppManagerImpl.handleGetAppAssistantRequest(AppManagerImpl.java:725) ~[?:?]
        at io.openems.edge.core.appmanager.AppManagerImpl.lambda$buildJsonApiRoutes$34(AppManagerImpl.java:823) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.lambda$handleRequest$4(JsonApiBuilder.java:106) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.lambda$rpc$7(JsonApiBuilder.java:214) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiEndpoint.handle(JsonApiEndpoint.java:63) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.handle(JsonApiBuilder.java:702) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.handle(JsonApiBuilder.java:661) ~[?:?]
        at io.openems.edge.controller.api.common.handler.ComponentRequestHandler.lambda$buildJsonApiRoutes$6(ComponentRequestHandler.java:139) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.lambda$rpc$9(JsonApiBuilder.java:289) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiEndpoint.handle(JsonApiEndpoint.java:63) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.handle(JsonApiBuilder.java:702) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.handle(JsonApiBuilder.java:661) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.lambda$delegate$10(JsonApiBuilder.java:325) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiEndpoint.handle(JsonApiEndpoint.java:63) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.handle(JsonApiBuilder.java:702) ~[?:?]
        at io.openems.edge.common.jsonapi.JsonApiBuilder.handle(JsonApiBuilder.java:661) ~[?:?]
        at io.openems.edge.common.jsonapi.SingleJsonApiBinder.handleRequest(SingleJsonApiBinder.java:82) ~[?:?]
        at io.openems.edge.controller.api.backend.BackendOnRequest.apply(BackendOnRequest.java:73) ~[?:?]
        at io.openems.common.websocket.OnMessageHandler.handleJsonrpcRequest(OnMessageHandler.java:83) ~[?:?]
        at io.openems.common.websocket.OnMessageHandler.run(OnMessageHandler.java:61) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

Reviewed-by: Johann Kaufmann <165755282+johannk24@users.noreply.github.com>