FEMS Backports (#2446)
* AppCenter: fix not automatically installing missing dependencies

user is null while resolving missing dependencies which resulted in a NullPointerException

```
2023-11-15T12:13:02,237 [orker-10] ERROR [appmanager.ResolveDependencies] Could not resolve dependencies!
java.lang.NullPointerException: Cannot invoke "io.openems.edge.common.user.User.getLanguage()" because "<parameter1>" is null
	at io.openems.edge.core.appmanager.AppManagerImpl.lambda$15(AppManagerImpl.java:517) ~[?:?]
	at io.openems.edge.core.appmanager.AppManagerImpl.lockModifyingApps(AppManagerImpl.java:892) ~[?:?]
	at io.openems.edge.core.appmanager.AppManagerImpl.handleAddAppInstanceRequest(AppManagerImpl.java:515) ~[?:?]
	at io.openems.edge.core.appmanager.ResolveDependencies.resolveDependencies(ResolveDependencies.java:108) ~[?:?]
	at io.openems.edge.core.appmanager.ResolveDependencies.run(ResolveDependencies.java:42) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
Everything still works there will only be AppCenter info and debugLog of a missing dependency if there are missing dependencies

* AppCenter: Integrated systems

* Edge: Check Battery Combination only if the battery is started

Check the combination of Battery and GoodWe only if the battery was started.
Set default values as long as the goodwe is not started.

* UI Time-Of-Use: refactor chart in Live modal

* Time-of-Use Controller: improvements for BETA test

- Add Penalize/Constraints for bad solutions
- Never apply charge for full batteries in run()
- Use ConsumptionPower for short term prediction instead of UnmanagedConsumptionPower
- Error in STROMDAO App on fems51290: validating ZIP_CODE
- Handle trailing non-available values for production/consumption/price
- Values of "StateMachine"-Channels are still sometimes decimals. Handle aggregation in Edge
- round enums to their most appearing value not average
- fix tibber app

* UI: Extending Systemexecute

- adding option to build and run debian-package (from a branch) on a fems
- changing field for custom commands from input to text-area

* UI: refactor channelthreshold history

Example for all relay data dependent charts -> active time over period

* added time to Chart types

* AppCenter: Home 20/30 available relays

Edge:
 - add possibility to filter components via ServiceUtils
 - moved HeatProps to common RelayProps
 - added Filter options to relays
 - changed cardinality of HeatPump, HeatingElement, CombinedHeatAndPower to MULTIPLE
 - updated ManualRelayControl, ThresholdControl to use Props
 - removed unnecessary relay helper methods and added/update some
 - fix checking if a relay is used when set inside an array
 - added option for MultiSelect of SelectGroup
 - added possibility for custom filters in CheckRelayCount
 - updated translations
 - added test for default relay ports for Home 10 & 30
 - added more apps to translation tests
 - added possibility to defined number of ios and io prefix for dummy input output

UI:
 - add possibility to set the option group picker to multi

* GoodWe Battery-Inverter: improve property descriptions

Rename the property name and description of "Enable Feed In To Grid", as the name and description are misleading.

* UI: fix format number not using configuration

* Charts: Using the configured format instead of an empty string

* TypeUtils: update coding style + handle NaN/Infinite

* UI: add check in prepareBatteryExtension for isRunning

* GoodWe: implement RippleControlReceiver; update config descriptions

This PR also includes
- general methods to set a channel write value until the read value is the same.
- improve titles/descriptions of GoodWe Battery-Inverter

* Time-of-Use Controller: improvements for BETA test

- Increase max calculation time to 11 minutes
- Use existingSchedule as basis for initial population
- Repair/Postprocess bad solutions

* GoodWe: revert SetWriteValueIfNotRead for ShadowEnable

* AppCenter: Home NoFeedInLimitation & correct RCR config

* Fix JUnit test

* Quick fix for Simulated EVCS

See https://community.openems.io/t/errors-in-simulating-evcs/2014/3

---------

Co-authored-by: Michael Grill <59126309+michaelgrill@users.noreply.github.com>
Co-authored-by: Sebastian Asen <47855186+sebastianasen@users.noreply.github.com>
Co-authored-by: Sagar Venu <32655208+venu-sagar@users.noreply.github.com>
Co-authored-by: Stefan Feilmeier <3515268+sfeilmeier@users.noreply.github.com>
Co-authored-by: Lorant Meszlenyi <16509320+hydroid7@users.noreply.github.com>
Co-authored-by: Lukas Rieger <73471197+lukasrgr@users.noreply.github.com>